language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t jablesyeah/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jablesyeah/react-test npm test

after_success:
  - docker build -t jablesyeah/multi-client ./client
  - docker build -t jablesyeah/multi-nginx ./nginx
  - docker build -t jablesyeah/multi-server ./server
  - docker build -t jablesyeah/multi-worker ./worker

